### ISSUE TITLE
Bug! Damaged french characters from JSON

### ISSUE THREAD

**Issue by generalov-viktar** [api-sports/public-roadmap#84]
`assist: {`
     `id: 110391`
     `name: "D. Forlï¿½n"`
`}`

from: v3/fixtures?id=208377

Ï¿½ is simply a substitute character (EF | BF | BD UTF-8) and is used to indicate problems when the system cannot display the correct character. This means that there is no way for you to convert ï¿½ to É.

**What to do in that case?**

**Comment by api-sports** [comment]
Hi,

Thanks for the info, we have fixed this. For bug support, contact us on our dashboard.

Best

**Comment by generalov-viktar** [comment]
You have not fully fixed this bug. If you look at the device id 208393, you will see this:
`player: {`
`id: 35647`
`name: "ï¿½. Pï¿½rez"``
